### ISSUE TITLE
Emitted node type for `&:extend`

### ISSUE THREAD

**Issue by jwilsson** [shellscape/postcss-less#123] opened 2018-10-31 20:35 UTC
* Node Version: `11.0.0`
* NPM Version: `6.4.1`
* postcss Version: `7.0.5`
* postcss-less Version: `3.0.2`

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

### LESS

```less
.a {
    &:extend(.b);
}
```

### JavaScript
N/A

### Expected Behavior
I'm not sure which node type `&:extend` should be parsed as. Right now it's `Decl` but I haven't decided if I think that's correct or if it should be a `Rule` yet. So I guess this is more of a question than an issue really.

[This test](https://github.com/shellscape/postcss-less/blob/a28a3295e31f106479e37990428f0a99827831e9/test/parser/extend.test.js#L33) makes it look intentional but I couldn't find anything about it in the changelog.

### Actual Behavior
Not really sure 😄 

### How can we reproduce the behavior?
Run `postcss-less` on the example above.

**Comment by hudochenkov** [comment] 2018-11-10 20:33
I think it should be a `Rule`, as it was before. And it will be in line with other [cases](https://github.com/shellscape/postcss-less/blob/master/test/parser/extend.test.js).

I faced this problem with an undocumented change from `Rule` to `Decl` in `&:extend(.class1);`, when was fixing `stylelint-order` compatibility for `stylelint@9.7.0+` which has new `postcss-less@3+` inside.

**Comment by fabb** [comment] 2018-11-14 18:40
So will this issue be closed with „wont‘t fix“? `prettier` is holding off updating to @3 until this is settled. https://github.com/prettier/prettier/issues/5420#issuecomment-438753526

**Comment by shellscape** [comment] 2018-11-14 18:54
@fabb that would be a bit premature - I'd like to give others interested in this an opportunity to respond to my last comment. Maybe a few more days.

I can say that I would disagree with the Prettier maintainer's opinion that it's hard to update. They are also incorrect that the new major version contained regressions - major versions often contain breaking changes. It's important to note that this was a change between PostCSS v5 and v7. postcss-less@3.0.0 updated to use PostCSS v7. Going against the grain of PostCSS isn't something that would be wise.

**Comment by hudochenkov** [comment] 2018-11-14 20:05
Less documentation [considers](http://lesscss.org/features/#extend-feature) `:extend` as a pseudo-class:

> Extend is a Less pseudo-class which merges the selector it is put on with ones that match what it references.

And it's mentioned as a selector, or extension of selectors through the documentation. Only rules could have a selector. So I think `postcss-less` should parse `&:extend()` as a `Rule` to be more in line with Less documentation and what users expect.

**Comment by shellscape** [comment] 2018-11-14 20:34
> And it's mentioned as a selector, or extension of selectors through the documentation.

I think that argument is a bit of a stretch and deserves more specificity; while it can be _used_ as a psuedo selector, the use of `&:extend` is not a selector nor is it a psuedo-selector.  Consider this example from their documentation:

```css
.a:extend(.b) {}   // < pseudo selector

// the above block does the same thing as the below block
.a {
  &:extend(.b);  // < neither, belongs to the ruleset along side of other declarations
```

> and what users expect.

When `&:extend(...)` is used within a ruleset, it's reasonable to expect that it would be treated as a declaration. It is after-all, applying (extending) a set of declarations onto the parent ruleset.

Additionally, being able to recognize a distinction between where/how `:extend` is used has value. A `Rule` with a pseudo class of `extend` is very clearly part of a `Rule`, whereas a `Decl` with `:extend` is very clearly part of the ruleset's other declarations.

I think we've identified two good ways to look at this, and they both have merit. I'm biased in that I think my reasons for keeping how it currently parses are a little stronger. But I think the deal-breaker against changing it lies in how PostCSS operates and what it returns to us, as it fairly strictly follows the CSS spec. While LESS diverges quite a bit, it doesn't provide a standard for _how_ a node should be represented (in any cases).

**Comment by hudochenkov** [comment] 2018-11-14 21:50
`&:extend(...);` indeed is a grey area for PostCSS. I have a similar example, but for `AtRule`:

```scss
.a {
  @include large-text;
}
.b {
  @include large-text {
  }
}
```

It's SCSS mixins, but it doesn't matter as it could be any other at-rule. PostCSS parses both of them as `AtRule` and not like `Decl` and `AtRule`. Maybe because they have examples in standard CSS: `@import` — at-rule without child nodes, `@media` — at-rule with child nodes. Unfortunatelly, I don't know similar example for a rule without block (`{}`) after a selector for standard CSS.

Making `&:extend();` as a declaration because it looks like one doesn't make sense, in my opinion.

Less syntax causes a lot of problems for authors of CSS tooling. Pretty often Less has some features, that other syntax doesn't have. `postcss-less` is our hope to have fewer issues while working with Less syntax. The work which was done with `postcss-less` is remarkable. I, as `stylelint` maintainer, see fewer issues with Less syntax than it was two years ago. I am grateful to people, who are working on `postcss-less`. Relying on `postcss-less` to handle unusual for other syntaxes cases is very beneficial for stylelint, Prettier, and probably other tools.

Keeping `&:extend();` as a declaration will keep developers of other CSS tools to have more code to recognize this special case, and every tool will handle it differently. Please, reconsider your decision for keeping it as it is now.

**Comment by shellscape** [comment] 2018-11-14 22:17
I appreciate your compliments and your passion for our little niche of the tooling world. While I'm not yet compelled to alter how the package currently behaves, we'll leave this open for a while yet to if anyone drops some comments which change that.

**Comment by shellscape** [comment] 2018-11-15 13:32
I've queued [this commit](https://github.com/shellscape/postcss-less/commit/dfb8b1b3e299b44a39b450936189c6b9828d8950) which adds an `extend` property onto `Rule` and `Decl` which use `:extend` and `&:extend`.

**Comment by shellscape** [comment] 2018-11-26 13:53
Since there hadn't been any follow-up comment, I've merged that commit. Will follow up with a new version release shortly.

**Closed by shellscape** 2018-11-26 13:53 UTC
Labels: c¹ ⋅ discussion
