### ISSUE TITLE
Bogus CssSyntaxErrors in 1.1.4

### ISSUE THREAD

**Issue by Nikerabbit** [shellscape/postcss-less#99] opened 2018-03-21 07:46 UTC
* Node Version: v7.0.0 (also tested v9.8.0)
* NPM Version: 3.10.8 (also tested 5.6.0)
* postcss-less Version: 1.1.4

### LESS
https://github.com/wikimedia/mediawiki-extensions-ContentTranslation/blob/0cacd98f21a0d378032a246189404e9e13680bc6/modules/dashboard/styles/ext.cx.dashboard.less
https://github.com/wikimedia/mediawiki-extensions-ContentTranslation/blob/0cacd98f21a0d378032a246189404e9e13680bc6/modules/ui/styles/mw.cx.ui.Columns.less

### Errors 

```
modules/dashboard/styles/ext.cx.dashboard.less
 12:3  ✖  Unexpected }   CssSyntaxError

modules/ui/styles/mw.cx.ui.ToolsColumn.less
 8:1  ✖  Unexpected }   CssSyntaxError
```

### Expected Behavior

No error or valid error. mw.cx.ui.Columns.less doesn't even have `}` anywhere near line 8. It is not clear to me what is special in these two files to cause such errors.

### Actual Behavior

Error that does not seem to make any sense.

### How can we reproduce the behavior?

Using version 1.1.4. Downgrading to 1.1.3 error does not happen.
```
git clone git@github.com:wikimedia/mediawiki-extensions-ContentTranslation.git
cd mediawiki-extensions-ContentTranslation
git checkout 0cacd98f21a0d378032a246189404e9e13680bc6
npm install
./node_modules/.bin/grunt stylelint
```

If you now edit `package.json` to force version 1.1.3 and install again, tests will pass.

Do note that you might encounter https://github.com/wikimedia/grunt-stylelint/issues/49 – but you can still see that it is failing or passing.

**Comment by YuliaTsareva** [comment] 2018-03-21 10:32
We also have an issue with 1.1.14 (via stylelint).

It shows an error on the line with `@import`.

```
 Unknown word (CssSyntaxError)] [CssSyntaxError] Unknown word (CssSyntaxError)
```

**Comment by yesmeck** [comment] 2018-03-21 12:30
Same here https://travis-ci.org/ant-design/ant-design/jobs/356190100#L5362

**Comment by shellscape** [comment] 2018-03-21 14:23
@yesmeck @YuliaTsareva and anyone else visiting this repo. **DO NOT** post "me too" replies. Use the reaction button on the original post. I will delete any further "me too" replies on this issue.

**Comment by shellscape** [comment] 2018-03-21 14:27
@HauptmannEck @catearcher looks like #97 broke some things for people. I'm going to have to revert that change until you all can find a fix.

**Comment by shellscape** [comment] 2018-03-21 16:34
@HauptmannEck @catearcher my mistake, it was #98 that introduced the problem.

@davidyorr I have reverted #98 and added sanity tests to the test suite. Using the first file that the OP provided, I can reproduce the error he's seeing, with your changes merged. I've left your tests in place, but commented out. You'll have to try another approach to resolving #92.

@Nikerabbit I'll be publishing a fix to NPM within the hour.

**Closed** 2018-03-21 16:35 UTC

**Comment by Krinkle** [comment] 2018-03-22 19:52
Thanks! :star:

**Comment by zeljkofilipin** [comment] 2018-03-27 11:39
🎉
