### ISSUE TITLE
Incorrect parsing selectors starting `.` and containing parenthesis `()`

### ISSUE THREAD

**Issue by evilebottnawi** [shellscape/postcss-less#71] opened 2017-05-07 17:34 UTC
* Node Version: `7.10.0`
* NPM Version: `4.2.0`
* postcss-less Version: `0.16.1`

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

### LESS

```less
.foo:not(.a) {}
```

### JavaScript

```js
import postCssLess from 'postcss-less';
const less = `.foo:not(.a) {}`;
const root = postCssLess.parse(less);
```

### Expected Behavior

`rule.parent.nodes[0].params` should be not defined (property should be not exists)

### Actual Behavior

`rule.parent.nodes[0].params` is `true`

### How can we reproduce the behavior?

Use example in `javascript` section.

Issue was created based on https://github.com/stylelint/stylelint/issues/1741

**Comment by shellscape** [comment] 2017-05-07 17:41
Thanks for reporting! Duplicate of #56. This should be resolved by https://github.com/shellscape/postcss-less/pull/68.

**Closed by shellscape** 2017-05-07 17:41 UTC

**Comment by evilebottnawi** [comment] 2017-05-07 17:50
@shellscape good! If I can find the time today, I'll look through the solution code (PR) :+1:
